language: node_js
node_js: "12"

cache:
  - yarn
install:
  - yarn

stages:
  - name: test
    if: branch IN (master)
  - name: release
    if: tag IS present
  - name: gitbook
    if: branch IN (master) && type IN (pull_request)

jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn test
      on:
        branch: master
    - stage: gitbook
      install:
        - yarn global add gitbook-cli
        - gitbook install
      script:
        - gitbook build . ./build
      deploy:
        provider: pages
        keep-history: true
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: build
        name: $GIT_NAME
        email: $GIT_EMAIL
    - stage: release
      script: yarn compile
      deploy:
​        provider: npm
​        email: $NPM_EMAIL
​        api_key: $NPM_TOKEN
​        skip_cleanup: true
​        on:
​          tags: true
