os: linux
language: node_js
node_js: "10"

cache:
  - yarn
install:
  - yarn

stages:
  - name: test
  - name: gitbook
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn test
    - stage: gitbook
      install:
        - yarn global add gitbook-cli
        - gitbook install
      script:
        - gitbook build . ./build
      deploy:
        provider: pages
        keep-history: true
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: build
        name: $GIT_NAME
        email: $GIT_EMAIL
        on:
          branch: master
    - stage: deploy
      script: yarn compile
      before_deploy:
        - cd dist
      deploy:
​        provider: npm
​        email: $NPM_EMAIL
​        api_key: $NPM_TOKEN
​        skip_cleanup: true
​        on:
​          tags: true
